### ISSUE TITLE
Lernelemente, -räume und -welten per Drag and Drop in Workspace importieren

### ISSUE THREAD

**Issue by andreasweishaupt** [ProjektAdLer/Autorentool#110]
**User Story**

Als Lehrender möchte ich exportierte Adler-Dateien per Drag and Drop in den Workspace importieren können.

 

**Akzeptanzkriterien**

- [x] Exportierte Adler-Dateien können per Drag and Drop in den Workspace geladen werden

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by niklasstich** [comment]
Uns gefällt die aktuelle Drop-Zone Implementierung noch nicht ganz. Aktuell ist es nur ein kleines Feld in dem Workspace, wir hätten es aber gerne über die gesamte Fläche des Programms.
