### ISSUE TITLE
Übersicht über erstellte Lernwelten

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#120]
Als Lehrender möchte ich jederzeit eine Übersicht über meine zuletzt geöffneten Lernwelten haben.

 

**Akzeptanzkriterien**

- [x] Beim Start des Autorentools wird die Lernweltübersicht angezeigt
- [x] Es werden alle gespeicherten Lernwelten in der Übersicht angezeigt
- [x] Die Auswahl einer Lernwelt öffnet diese Lernwelt in der Hauptansicht
- [x] Die aktuell geladenen Lernwelten werden hervorgehoben
- [x] Über einen Plus-Button kann eine neue Lernwelt erstellt werden
- [x] Über den X-Button auf einer Lernwelt kann eine Welt aus der Übersicht gelöscht werden
- [x] Über einen Laden-Button kann eine gespeicherte Lernwelt der Übersicht hinzugefügt werden

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by andreasweishaupt** [comment]
![image](https://github.com/ProjektAdLer/Autorentool/assets/31248215/416ba711-bc84-4e52-80c4-c369be321b2b)
