### ISSUE TITLE
Lernwelt erstellen

### ISSUE THREAD

**Issue by Teigler** [ProjektAdLer/Autorentool#13]
Als Lehrender möchte ich eine Lernwelt erstellen können.

 

**Akzeptanzkriterien**

- [x] A1: Lernwelt erstellen muss laut dem Aktivitätsdiagramm "Create learning world" implementiert werden.

- [x]  A2: Im Autorentool müssen Button so gestaltet sein, dass sie mit folgenden Eingabegeräten bearbeitet werden können: Maus, Stift, Finger

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by niklasstich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/13?planning-poker) with ZenHub @andreasweishaupt @DimitriB01 @e01118 @Teigler

**Comment by niklasstich** [comment]
![image](https://user-images.githubusercontent.com/32730297/160775724-5fed752b-416e-491c-adb4-330003764a84.png)
