### ISSUE TITLE
Aktionen wiederherstellen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#133]
Als Lehrender möchte ich eine oder mehrere Aktionen innerhalb einer Lernwelt wiederherstellen können (Redo).

 

**Akzeptanzkriterien**

- [ ] mit Vorwärts-Pfeil "Redo" einleiten
- [ ] mit Tastenkombination Strg + Umschalt + Z **ODER** Strg + Y "Redo" einleiten

 **Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden Beteiligten klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

 
**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [ ] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by niklasstich** [comment]
Technische Vorraussetzungen für dieses Feature werden in https://github.com/ProjektAdLer/Autorentool/issues/178, https://github.com/ProjektAdLer/Autorentool/issues/179, https://github.com/ProjektAdLer/Autorentool/issues/180 und https://github.com/ProjektAdLer/Autorentool/pull/173 gelegt. Siehe zudem #132 als Gegenstück.
