### ISSUE TITLE
Sprache einstellen

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#140]
**User Story**

Als Lehrender möchte ich die Sprache des Autorentools einstellen können. 

**Akzeptanzkriterien**

- [x] Sprachen Deutsch und Englisch einstellbar
- [x] Bei Änderung ändert sich die Anzeigesprache der Software zur Laufzeit (siehe #114)
- [x] Standardmäßig soll Deutsch ausgewählt sein
- [x] Zur Auswahl der Sprache soll über Radio Buttons funktionieren

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik.png](https://images.zenhubusercontent.com/61bb4c06e5ae7e611d7d0fc8/5b062572-7d4a-45b2-82ff-5dd088d5ae11)

**Comment by niklasstich** [comment]
![image](https://user-images.githubusercontent.com/32730297/206250550-cc1a39c2-368d-4645-b38f-3a20f241e1d8.png)
