### ISSUE TITLE
Lernelemente, -räume und Lerninhalte per Drag and Drop an richtiger Position einfügen

### ISSUE THREAD

**Issue by andreasweishaupt** [ProjektAdLer/Autorentool#149]
**User Story**

Als Lehrender möchte ich Lernräume, -Elemente, sowie Lerninhalte, wie Videos, Bilder, H5P oder Pdf direkt in die Oberfläche ziehen können und diese sollen an dieser Position in der Welt oder im Raum erstellt werden (Verbesserung von #83 und #110 )

 

**Akzeptanzkriterien**

- [ ] Importierte Adler-Dateien, die Räume oder Elemente enthalten werden an der Position in der Welt oder im Raum platziert, an die sie gezogen wurden
- [ ] Das Lernelement wird nach dem Schließen des CreateElementDialog in dem Slot erstellt, an die die Lerninhalt-Datei in der Oberfläche gezogen wurde (sowohl Datei von außen als auch aus "Meine Dateien")
- [ ] Wenn Lerninhalt-Datei auf "Meine Dateien" Fenster gezogen wird, soll die Datei stattdessen dort abgelegt werden
- [ ] Während Drag und Drop soll über den DropZones eine Erklärung erscheinen

 **Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden Beteiligten klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

 
**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [ ] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
Erledigt #233
