### ISSUE TITLE
H5P Elemente in die MBZ Datei einbauen

### ISSUE THREAD

**Issue by DimitriB01** [ProjektAdLer/Autorentool#150]
**User Story**

Als User möchte ich H5P Elemente in Moodle hochladen können.

**Akzeptanzkriterien**

- [x] Das ausgewählte H5P Element ist in Moodle dargestellt
- [x] Das ausgewählte H5P Element wird fehlerfrei in Moodle angezeigt

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by DimitriB01** [comment]
![XmlH5PFactory](https://user-images.githubusercontent.com/92084464/187385674-8d1cb288-9409-452c-beb1-12393e1e66a9.png)

**Comment by DimitriB01** [comment]
![XmlH5PFactory](https://user-images.githubusercontent.com/92084464/187386114-070d33b9-f9fb-4b65-bdea-9f76305dbff1.png)

**Comment by niklasstich** [comment]
Wurde ausführlich von Dimitri und Philipp getestet.
