### ISSUE TITLE
Text-Dateien als Lernelement einbinden

### ISSUE THREAD

**Issue by MarvinHo64** [ProjektAdLer/Autorentool#152]
**User Story**

Als Lehrender möchte Text-Dateien als Lernelement einbinden können.

 

**Akzeptanzkriterien**

- [x] Typ in ModalDIalog auswählbar
- [ ] <del> Auswahl der Programmiersprache für mögliches Syntaxhighlighting </del>
[Programmiersprache kann anhand von Dateiendung erfasst werden]
- [x] Datei importieren

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by DimitriB01** [comment]
Vielleicht benennen wir dieses Lernelement in "Datei" um?

**Comment by MarvinHo64** [comment]
![Entities](https://user-images.githubusercontent.com/96189400/196421162-eec02a4f-c1dc-40f6-aa84-4b7dec258163.PNG)

**Comment by MarvinHo64** [comment]
![ViewModels](https://user-images.githubusercontent.com/96189400/196421198-02da474e-46a9-4f73-8927-86720df155a5.PNG)

**Comment by DimitriB01** [comment]
![image](https://user-images.githubusercontent.com/92084464/197523320-701419a4-d77c-4935-ba20-eb0f559dc87f.png)
