### ISSUE TITLE
Kaskadieren von neu erstellen Objekten in Lernwelt/-raum

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#153]
**User Story**

Als Lehrender möchte ich, dass erzeugte Objekte in der Oberfläche nicht genau übereinander, sondern versetzt dargestellt werden um die Sichtbarkeit zu verbessern

 

**Akzeptanzkriterien**

- [x] Darstellung der Objekte nicht übereinender, sondern kaskadiert (evtl. immer 5 mal in Folge, dann wieder von vorne)
- [x] Rahmen um die Darstellungen herum, um noch besser hervorzuheben

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by andreasweishaupt** [comment]
![image](https://user-images.githubusercontent.com/31248215/203793486-932e56c3-8bdb-4950-887b-1fe6bfc49a00.png)
Erstellte Lernräume und -elemente werden versetzt erstellt. Das elfte Objekt wird wieder an der Position vom ersten erstellt.
