### ISSUE TITLE
Beim Start des Autorentools ist es nur möglich eine Lernwelt anzulegen oder zu laden

### ISSUE THREAD

**Issue by DimitriB01** [ProjektAdLer/Autorentool#154]
**User Story**

Als Lehrender möchte ich, wenn das Autorentool noch keine Lernwelt beinhaltet, nur die Möglichkeit haben eine Lernwelt zu erstellen oder zu laden. (Andere Buttons werden offensichtlich ausgegraut.)
 

**Akzeptanzkriterien**

- [x] Falls keine Lernwelt im Autorentool geladen ist, kann der User nur eine Lernwelt erstellen. 

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik.png](https://images.zenhubusercontent.com/61bb4c06e5ae7e611d7d0fc8/d46465ca-ba25-416d-9bca-af40d4bf2b3c)
