### ISSUE TITLE
Bei Erstellen von Lernwelt sofort auswählen

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#155]
**User Story**

Als Lehrender möchte ich, dass beim Erstellen einer neuen Lernwelt diese sofort ausgewählt und in der View angezeigt wird.
 

**Akzeptanzkriterien**

- [x] Welt in Viewmodel auf Fokus setzen
- [x] Alle Views updaten

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by niklasstich** [comment]
Im CreateLearningWorld Command implementiert

**Comment by andreasweishaupt** [comment]
![image](https://user-images.githubusercontent.com/31248215/196952084-ee238d67-ab1e-46e0-81f1-9b49b8b20bbd.png)
