### ISSUE TITLE
[Technical] Benötigte Testabdeckung erreichen 

### ISSUE THREAD

**Issue by DimitriB01** [ProjektAdLer/Autorentool#159]
Dataaccess  = Dimitri
PresentationLogic = Marvin
View = Niklas 
DropZone, Components & bei bedarf helfen = Andreas

**Comment by niklasstich** [comment]
Mit Commit 5716995630cd4a303961606e1932ebfacc1a85b7 haben wir ca. 95% Testabdeckung erreicht (siehe [hier](https://coveralls.io/builds/51515543)).
