### ISSUE TITLE
Punkte für Lernelemente

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#190]
**User Story**

Als Lehrender möchte ich Punkte für Lernelemente angeben können.

 

**Akzeptanzkriterien**

- [x] An einem Lernelement muss eine Punktzahl angegeben werden können, die bei Abschließen des Elements gewährt werden
- [x] Die Information, wie viele Punkte das Lernelement gewährt, muss an das 3D Tool übergeben werden (DSL)
- [x] #194

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by DimitriB01** [comment]
![image](https://user-images.githubusercontent.com/92084464/197523273-0cfa86a1-057d-431f-8a78-aa3c46121e47.png)
