### ISSUE TITLE
Punkte für Lernräume

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#191]
**User Story**

Als Lehrender möchte ich eine benötigte Punktzahl für Räume angeben können, die mindestens erreicht werden soll um den Raum abzuschließen.

 

**Akzeptanzkriterien**

- [x] Anzeige, wie viele Punkte der Raum insgesamt enthält (Summe der Elemente)
- [x] Eingabefeld, wie viele Punkte benötigt sind
- [x] Benötigte Punkte über DSL an 3D weitergeben
- [x] (Optional) Anzeige, wie viel Prozent vom Gesamtpunktzahl benötigt werden
![image.png](https://images.zenhubusercontent.com/61bb022b512af1a88b458232/77b4583a-72e0-49aa-9e09-55728da0c1a6)

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen
- [x] #190 abgeschlossen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by DimitriB01** [comment]
![image](https://user-images.githubusercontent.com/92084464/197525592-bf48cb44-b59d-48b1-9c95-70371185c8c4.png)

**Comment by DimitriB01** [comment]
So sehen die Punkte eines LearningSpace in der DSL aus.

**Comment by andreasweishaupt** [comment]
![image](https://user-images.githubusercontent.com/31248215/203788226-28acc900-88a0-406f-b0c3-8f0045cfa8a8.png)
Im Erstellen-Dialog für Lernräume kann die für den Raum benötigte Anzahl an Punkten angegeben werden. Im Edit-Dialog wird zusätzlich angezeigt, wieviel Punkte alle in diesem Lernraum enthaltenen Lernelemente zusammen haben. Die Anzeige im Dialog muss eventuell noch angepasst werden.

**Comment by andreasweishaupt** [comment]
![image](https://user-images.githubusercontent.com/31248215/203791600-b13c5dff-397e-4263-a117-46379209ca1d.png)
![image](https://user-images.githubusercontent.com/31248215/203791761-beafaea8-d8d3-4a09-a736-35e286b0fffe.png)
