### ISSUE TITLE
Lernwelt bearbeiten

### ISSUE THREAD

**Issue by Teigler** [ProjektAdLer/Autorentool#21]
Als Lehrender möchte ich eine Lernwelt bearbeiten können.

 

**Akzeptanzkriterien**

- [x] A1: Lernwelt bearbeiten muss laut dem Aktivitätsdiagramm "Update learning world" implementiert werden.
- [x] A2: Maus/Stift/Finger?

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by DimitriB01** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/21?planning-poker) with ZenHub @e01118 @Teigler @niklasstich @andreasweishaupt

**Comment by niklasstich** [comment]
![image](https://user-images.githubusercontent.com/32730297/160777505-14a90930-61ee-432c-ad61-62c41b32f3c2.png)
