### ISSUE TITLE
Lernwelt löschen

### ISSUE THREAD

**Issue by Teigler** [ProjektAdLer/Autorentool#22]
Als Lehrender möchte ich eine Lernwelt löschen können.

 

**Akzeptanzkriterien**

- [x] Als Lehrender möchte ich eine bestehende Lernwelt per Knopfdruck löschen können (Akti Delete learning world)

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by niklasstich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/22?planning-poker) with ZenHub @andreasweishaupt @DimitriB01 @e01118 @Teigler

**Comment by niklasstich** [comment]
![image](https://user-images.githubusercontent.com/32730297/160777121-b0226b87-9261-43c6-b4a1-2fdbf12edb47.png)
