### ISSUE TITLE
Übersicht über die Lernwelt sehen (Baum)

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#227]
Als Lehrender möchte ich eine Übersicht (Baum) über die Lernwelt haben.

 

**Akzeptanzkriterien**

- [x] Reiter auf- und zuklappbar
- [x] Lernräume aufklappabr, um Lernelemente zu sehen
- [x] Icons neben Räumen/Elementen

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik.png](https://images.zenhubusercontent.com/61bb4c06e5ae7e611d7d0fc8/0b4d8ccc-8f79-4b9e-98e1-8d4f3f3b805d)

**Comment by MarvinHo64** [comment]
![grafik](https://user-images.githubusercontent.com/96189400/205908104-87d428a3-bcd8-4572-b2dd-0b99a180be95.png)
