### ISSUE TITLE
Lernelemente in den Grundriss platzieren

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#233]
Als Lehrperson möchte ich Lernelemente im Grundriss des Lernraums platzieren

 

**Akzeptanzkriterien**

- [x] Anzeige der Icons der Lernelemente 
- [x] Auswählen der Lernelemente in den Grundriss per linken Mausklick
- [x] Hinzufügen der Lernelemente in den Grundriss (mittleres Fenster) per Drag&Drop durch Drop auf Grundrissslot
- [x] Bei Drag&Drop eines unplazierten Elements in belegten Slot Dialog ob ersetzt werden soll
- [x] Bei Drag&Drop eines plazierten Elements in belegten Slot Lernelemente tauschen
- [x] Bei Drag&Drop eines plazierten Elements in einen freien Slot Lernelement in diesen Slot verschieben

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik.png](https://images.zenhubusercontent.com/61bb4c06e5ae7e611d7d0fc8/f2c1ffbc-f375-47b6-a19e-91d8b752b2cb)

**Comment by andreasweishaupt** [comment]
![image](https://github.com/ProjektAdLer/Autorentool/assets/31248215/b246af84-6686-4cd5-87c9-b660521f651d)
