### ISSUE TITLE
[Bug] Räume die bereits vorhanden sind, werden von geladenen Räumen überschrieben.

### ISSUE THREAD

**Issue by DimitriB01** [ProjektAdLer/Autorentool#238]
## Beschreibung des Problems:
- Wenn ein gespeicherter Raum 2 mal geladen wird, dann werden die 2 Space-Objekte übereinander gelegt, sodass der untere nicht mehr anklickbar ist. 
- Wenn ein Raum erstellt wird, gespeichert und anschließend geladen wird, dann sind beide Elemente aneinander "geklebt". 
## Schritte zum Reproduzieren:
1. Welt erstellen
2. Space erstellen
3. Space speichern
4. Den gespeicherten Space laden 
5. Eines der beiden Space-Objekte bewegen
## Erwartetes Verhalten:
Beide Räume und enthaltene Elemente sind unabhängig von einander und können mehrfach geladen werden.
## Tatsächliches Verhalten: 
Das verschieben und bearbeiten der Räume ändert beide Raum-Objekte.

**Comment by niklasstich** [comment]
Problem ist, dass Id gespeichert und wiederhergestellt wird.
Lösung: Id in World, Space und Element als DataMember rausnehmen. Stattdessen in [OnDeserialized](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.ondeserializedattribute?view=net-6.0) eine neue ID vergeben.

**Comment by MarvinHo64** [comment]
Fixed in 21f7b42f

**Comment by DimitriB01** [comment]
Funktioniert wie gewünscht 👍
