### ISSUE TITLE
[Bug] Lernelemente werden nicht korrekt gespeichert

### ISSUE THREAD

**Issue by DimitriB01** [ProjektAdLer/Autorentool#239]
## Beschreibung des Problems:
Beim Speichern eines Lernelements (Content getestet mit Image und Text) kommt 
## Schritte zum Reproduzieren:
1. Welt erstellen
2. Space erstellen
3. Element erstellen
4. Element Speichern
## Erwartetes Verhalten:
Element wird korrekt ohne Fehlermeldungen gespeichert.
## Tatsächliches Verhalten:
Eine Exception erscheint, das Element konnte nicht serialisiert werden.

**Comment by DimitriB01** [comment]
![image](https://user-images.githubusercontent.com/92084464/196141876-d8654902-1c64-485e-b944-5b9c4ee703bf.png)

**Comment by niklasstich** [comment]
Guter Catch. Habe noch gar nicht versucht, Lernelemente einzeln abzuspeichern.

**Comment by niklasstich** [comment]
Test in a1dfe4dfaebab283d80428f6e6b3c3d35c18aedc, fixed in 88968ec0512d71e5ab7c171ae763c9a83c91a36d

@DimitriB01 Bitte nochmal überprüfen, ob es behoben ist.

**Comment by DimitriB01** [comment]
Funktioniert wie gewünscht 👍
