### ISSUE TITLE
Lernraum speichern

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#24]
Als Lehrender möchte ich einen Lernraum speichern können.

 

**Akzeptanzkriterien**

- [x] Aktivitätsdiagramm "persist learning space" erstellen
- [x] Lernraum speichern muss laut dem Aktivitätsdiagramm "Persist learning space" implementiert werden.

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by niklasstich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/24?planning-poker) with ZenHub @andreasweishaupt @DimitriB01 @e01118 @Teigler

**Comment by andreasweishaupt** [comment]
![image](https://user-images.githubusercontent.com/31248215/164167501-471bdc3f-999f-48d2-a598-7b9767e9a6d8.png)
