### ISSUE TITLE
Abhängigkeiten zwischen Lernräumen mit Und/Oder Bedingungen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#242]
Als Lehrender möchte ich mithilfe von UND/ODER-Bedingungen Abhängigkeiten von Lernräumen herstellen können.

 

**Akzeptanzkriterien**

- [x] Und-Bedingungen 
- [x] Oder-Bedingung
- [x] auswählbares Icon
- [x] Keine Zirkelschlüsse erlaubt
- [x] Keine zwei Pfeile in ein Element, wenn versucht wird Dialog für neue Bedingung
- [x] #243

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik.png](https://images.zenhubusercontent.com/61bb4c06e5ae7e611d7d0fc8/67e72939-cc55-49a8-908b-ddf51ce452dc)

**Comment by e01118** [comment]
![grafik.png](https://images.zenhubusercontent.com/61bb4c06e5ae7e611d7d0fc8/96fe72b0-645f-4f28-bebe-f6cfdecb3cd9)

**Comment by e01118** [comment]
![grafik.png](https://images.zenhubusercontent.com/61bb4c06e5ae7e611d7d0fc8/36be3ece-3522-4d17-9732-8e629a8d2227)

**Comment by MarvinHo64** [comment]
![grafik](https://user-images.githubusercontent.com/96189400/205647773-b36000d0-494e-4aa7-a1c7-d8d3524e98b0.png)
