### ISSUE TITLE
[Technical] Sidebar und SidebarItem Components

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#246]
Für die Slidermenüs links und rechts in #245 brauchen wir 3 neue Komponenten:
- Ein SliderComponent ganz außen, der die Buttons und Container beinhaltet und die Logik der Buttons steuert (nur ein Container auf, bei Buttonklick alle andere Container zu und neuen Container auf).
- Ein SliderContainer, der die Ansicht in dem Slider enthält.
- Ein SliderButton, der die Anzeige der SliderContainer über das SliderComponent steuert.
Im Bild SliderComponent in rot, SliderContainer in grün, SliderButton in blau
![image](https://user-images.githubusercontent.com/32730297/197548414-3a8ec71c-5c40-49fc-b0f8-05098297625d.png)

**Comment by e01118** [comment]
![grafik.png](https://images.zenhubusercontent.com/61bb4c06e5ae7e611d7d0fc8/85b2978d-6ea0-4ec5-87e0-14dff014389d)
