### ISSUE TITLE
[Bug] Extern erstellte Lernraum/elemente in eigene Lernwelt laden 

### ISSUE THREAD

**Issue by MarvinHo64** [ProjektAdLer/Autorentool#252]
## Beschreibung des Problems:
Wenn ein Lernelement oder ein Lernraum/Lernwelt mit Elementen, die auf einem anderen Rechner erstellt wurde, in das Autorentool geladen und die Lernwelt exportiert wird, hängt sich das Programm auf.
## Schritte zum Reproduzieren:
siehe oben
## Erwartetes Verhalten:
Aussagekräftige Fehlermeldung für User. Option, Pfad zum Elementinhalt neu anzugeben oder Elementinhalte in gespeichertem Objekt berücksichtigen. 
## Tatsächliches Verhalten:
Fehler wird geworfen, Programm hängt sich auf.
## Ansprechpartner:
@AdLer-Lukas 
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by niklasstich** [comment]
Liegt daran, dass Content Files nicht mit in der Welt serialisiert werden. Problemlösung:
1. Exportfunktion, mit der der Content einer Welt zusammen mit der Welt selbst gespeichert wird
1. Wie vorgeschlagen, aussagekräftige Fehlermeldung, falls Save File geladen wird und Content Dateien nicht vorhanden sind (mit Hinweis auf die Exportfunktion)

**Comment by niklasstich** [comment]
Blockiert, bis #306 implementiert ist

**Comment by niklasstich** [comment]
Punkt 2. hat sich durch #365 erledigt
