### ISSUE TITLE
[Bug] Lernwelt mit Pfaden zwischen Lernräumen kann nicht geladen werden.

### ISSUE THREAD

**Issue by MarvinHo64** [ProjektAdLer/Autorentool#254]
## Beschreibung des Problems:
Wenn Lernwelt mit Pfaden geladen wird, erscheint eine Fehlermeldung und das Laden erfolgt nicht.
## Schritte zum Reproduzieren:
1. Lernwelt erstellen
2. Mind. 3 Lernräume erstellen
3. Lernpfade zwischen den Lernräumen ziehen
4. Lernwelt speichern
5. Lernwelt laden
## Erwartetes Verhalten:
Lernwelt wird korrekt geladen.
## Tatsächliches Verhalten:
Fehlermeldung erscheint. Welt wird nicht geladen.

![grafik](https://user-images.githubusercontent.com/96189400/200556357-9542b4f8-2b3d-4500-b6f0-6bbecd986694.png)

## Ansprechpartner:
@AdLer-Lukas 
## Ursache (erst bei Fix angeben): 
Inkorrekte AfterMap Anweisung im Mapping Profil von LearningPathwayPe zu LearningPathway in welcher fälschlicherweise allen Spaces neue IDs zugewiesen wurde, sofern sie in einem LearningPathway enthalten sind. Dadurch konnten wir nicht mehr die richtigen Objekte finden, und da keine Guids mitserialisiert werden wurde dann nach einem Space mit Guid 0 gesucht.
## Lösung (erst bei Fix angeben): 
Das AfterMap herausnehmen und in allen Automapper Konstruktoren statt der Guid.Empty (0) eine neue Guid vergeben.
## Commit, in dem das Problem gefixed wurde:  
830e3ab8b6f3989bc203ae24359bc07494b1e544

**Comment by niklasstich** [comment]
Fehler vermutlich im OnDeserialized/ing von der Lernwelt

**Comment by niklasstich** [comment]
Fehler reproduzierbar mit [bug254.awf.zip](https://github.com/ProjektAdLer/Autorentool/files/10005851/bug254.awf.zip)

**Comment by niklasstich** [comment]
Aus irgendeinem Grund wird beim Mapping von LearningWorldPe zu LearningWorld vor 
```
            .AfterMap((s, d) =>
            {
                foreach (var pathWay in d.LearningPathways)
                {
                    pathWay.SourceSpace = d.LearningSpaces.First(x => x.Id == pathWay.SourceSpace?.Id);
                    pathWay.TargetSpace = d.LearningSpaces.First(x => x.Id == pathWay.TargetSpace?.Id);
                }
            })
``` 
die GUID des SourceSpace des zweiten Pathway auf 0 gesetzt: 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/32730297/201740901-3034dec5-4630-4258-aa37-97ba67da8f1d.png">
