### ISSUE TITLE
[Bug] Datei mit Sonderzeichen laden schließt Fenster

### ISSUE THREAD

**Issue by MarvinHo64** [ProjektAdLer/Autorentool#256]
## Beschreibung des Problems:
Lerninhalte mit Sonderzeichen im Dateinamen können nicht geladen werden.  
## Schritte zum Reproduzieren:
Ich habe ein Lernelement erstellt und dann die File mit dem Namen "SLOC PLOC C++.h5p" ausgewählt. Nach dem Klick auf den Button "Öffnen" hat sich das Fenster dann einfach geschlossen. Element wurde nicht erstellt.
Nach Änderung des Dateinamens hat auf "SLOC PLOC.h5p" hat es dann funktioniert.
## Erwartetes Verhalten:
Lernelement wird mit ausgwähltem Inhalt erstellt. 
## Tatsächliches Verhalten:
Dialog schließt sich, Element wird nicht erstellt.
## Ansprechpartner:
@AdLer-Lukas , @MarvinHo64 
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by niklasstich** [comment]
Fehler vermutlich im ContentHandler oder in der Logik für die Namensvergabe

**Comment by MarvinHo64** [comment]
Fixed durch neue UI
