### ISSUE TITLE
[Bug] 2 Elemente mit gleichem Namen verhindern Export

### ISSUE THREAD

**Issue by MarvinHo64** [ProjektAdLer/Autorentool#257]
## Beschreibung des Problems:
Wenn eine Lernwelt mit mind. 2 Elementen mit gleichen Namen exportiert wird, tritt eine unhandled exception auf.
1. Welt erstellen
2. Zwei Räume erstellen
3. In jeden der Räume ein Element mit gleichem Namen erstellen
4. Welt exportieren
## Erwartetes Verhalten:
Export funktioniert bzw. zweites erstelltes Element erhält abgeänderten Namen (z.B Element(1) )
## Tatsächliches Verhalten:
![Bildschirmfoto 2022-11-09 um 13 08 30](https://user-images.githubusercontent.com/96189400/200826625-9687dfbe-cfa8-438b-abb3-bd71b3caf996.png)

## Ansprechpartner:
@AdLer-Lukas , @MarvinHo64 
## Ursache (erst bei Fix angeben): 
Beim erstellen der Lernelement-Dateien, wird lediglich der Name hergenommen. Dabei kommt es zu einem Problem, wenn das System versucht eine Bereits erstellte Datei nochmals zu erstellen. 

## Lösung (erst bei Fix angeben): 
Vor dem erstellen der DSL werden die Namen aller Lernelemente auf Duplikate überprüft. Falls Duplikate vorkommen werden die Lernelement-Namen mit aufsteigenden Zahlen erweitert (1), (2) usw. Somit es möglich, dass Lernelemente gleiche Namen haben. Dabei ist es egal ob sie in einem anderen, im gleichen oder gleichnamigen Space sind.

## Commit, in dem das Problem gefixed wurde:  
5a5e8de449f59047edd44d0e614d9c5f476f6ab0

**Comment by niklasstich** [comment]
Fehler im Generator, @DimitriB01

**Comment by DimitriB01** [comment]
Notiz an mich selbst: Elemente innerhalb eines Spaces dürfen nicht gleich heißen. Wenn 2 Elemente den selben Namen und dieselbe Dateiendung haben ist es erlaubt, wenn diese Elemente zu verschiedenen Spaces zugeordnet sind.

Möglicher Ansatz: Element erstellen mit SpaceName_ElementName.ElementType

**Comment by DimitriB01** [comment]
Bei der derzeitigen Funktionsweise dürfen identische Elemente (Name + Dateiendung identisch) in unterschiedlichen Spaces existieren, wenn die unterschiedlichen Spaces einen NICHT identischen Namen haben (Space_1, Space_1 wäre nicht erlaubt)

**Comment by DimitriB01** [comment]
Commit folgt erst noch (muss Tests anpassen :D)

**Comment by DimitriB01** [comment]
Habe es nochmals geändert und gepushed. Es werden nun aufsteigende Zahlen (1), (2) am Ende des Lernelement-Namen angehängt, wenn es sich um ein Duplikat handelt. Zu sehen sind diese Änderungen beim Export in der DSL-Datei und somit auch in Moodle und in der 2d3d anwedung
