### ISSUE TITLE
Lernraum bearbeiten

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#26]
Als Lehrender möchte ich einen Lernraum bearbeiten können.

 

**Akzeptanzkriterien**

- [x] A1: Lernraum bearbeiten muss laut dem Aktivitätsdiagramm "Update learning space" implementiert werden.
- [ ] A2: Maus/Finger/Stift

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by andreasweishaupt** [comment]
![image.png](https://images.zenhubusercontent.com/61c19a042da0221af8fdae96/45c1b1ef-3ae0-48c1-8216-c098efe72201)
