### ISSUE TITLE
[Bug] Zeilenumbrüche in "Goals" Feld werden ignoriert

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#263]
## Beschreibung des Problems:
Wenn man ein Lernraum erstellt und Text in das "Goals" Feld schreibt oder kopiert, werden Zeilenumbrüche in diesem Feld ignoriert, das es ein einzeiliges Textfeld und kein Multiline-Textfeld ist.
Vermutlich existiert der selbe Fehler bei dem "Description" Feld.
## Schritte zum Reproduzieren:
1. Welt erstellen
2. Space erstellen und Text mit Zeilenumbrüchen in das "Goals" Feld reinkopieren
3. Backup erstellen und auf Moodle und Backend laden
## Erwartetes Verhalten:
Der im 3D angezeigte Text (also der im DSL abgelegte Text) enthält alle Zeilenumbrüche, welche eingegeben wurden.
## Tatsächliches Verhalten:
Alle Zeilenumbrüche gehen beim Kopieren verloren
## Ansprechpartner:
@niklasstich 
@MarvinHo64 
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by MarvinHo64** [comment]
Fixed durch neue Dialoge.
