### ISSUE TITLE
Menüleiste

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#269]
**User Story**

Als Lehrender möchte ich Menüleiste mit Funktionen angezeigt bekommen sodass ich Undo/Redo und oft benutzte Funktionen einfacher aufrufen kann.
 

**Akzeptanzkriterien**

- [x] Undo-Button
- [x] Redo-Button
- [x] Lernwelt Speichern
- [x] Lernwelt hochladen (MBZ)

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik](https://user-images.githubusercontent.com/57803816/226391564-3f561097-8aef-4b96-9da9-f651970e7661.png)
