### ISSUE TITLE
Lernraum löschen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#27]
Als Lehrender möchte ich einen Lernraum löschen können.
 

**Akzeptanzkriterien**

- [x] Akzeptanzkriterium "delete learning space" in Akti

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by DimitriB01** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/27?planning-poker) with ZenHub @andreasweishaupt @niklasstich @e01118 @Teigler

**Comment by andreasweishaupt** [comment]
![image.png](https://images.zenhubusercontent.com/61c19a042da0221af8fdae96/b9d7ee2c-3cda-41bf-8d12-518137659a44)
