### ISSUE TITLE
[Technical] Fehlermanagement konzeptionieren

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#292]
Wir brauchen einen Plan, wie wir schrittweise Fehlermanagement und Logging die Applikation einbauen können. In Folge diesen Issues müssen neue Issues/Tasks generiert werden für die Implementierung dieses Konzepts.

**Comment by Teigler** [comment]
Done siehe: 
https://wiki.projekt-adler.eu/de/AMG/KonzeptFehlerbehandlung
https://learn.microsoft.com/de-de/dotnet/core/extensions/logging?tabs=command-line
