### ISSUE TITLE
2D-Repräsentationen auswählen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#298]
Als Lehrender möchte ich für Lernelemente die 2D-Repräsentationen auswählen können, um die Darstellung der 3D-Modelle in der 3D-Lernumgebung nach meinen Wünschen wählen und den jeweiligen Lernraum nach meinen Vorstellungen gestalten zu können.

 

**Akzeptanzkriterien**

- [x] 2D-Repräsentationen: Tisch, Bücherregal, Automat --> aktuelle Liste: https://cloud.projekt-adler.eu/apps/files/?dir=/2D3D/3D_Design&fileid=2914
- [x] Auswahl an 2D-Repräsentationen orientiert sich an dem jeweiligen Typ des Lernelements
- [x] Auswahl über Dropdown
- [x] Naming für die einzelnen 2D-Repräsentationen bzw. 3D-Modelle (Punkt 4): https://wiki.projekt-adler.eu/de/AdLerEngine/Design/3DAssets_Uebersicht

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik](https://user-images.githubusercontent.com/57803816/235610790-b5e991f4-e26f-4cd9-ba9a-0839379cf69d.png)

**Comment by andreasweishaupt** [comment]
Eine Anforderung zusätzliche Anforderung ist, dass für den Autor immer alle 2D-Representationen zur Auswahl stehen. Die 2D-Representationen werden deshalb nicht in einem Dropdown sondern in einem Raster angezeigt, da die Dropdownliste sonst zu lang werden würde.
![image](https://github.com/ProjektAdLer/Autorentool/assets/31248215/1401c6f3-b39e-4072-b282-8be08420ed8c)

Die Reihenfolge, wie die 2D-Representationen angezeigt wird richtet sich nach dem ausgewählten Lernelemnttyp und dem Theme des Raums, in dem sich das Lernelement befindet.
Reihenfolge: 
1. Zufällig (standardmäßig ausgewählt)
2. 2D-Representationen, die zum Lerninhalttyp und zum aktuellen Theme passen
3. 2D-Representationen, die zum Theme passen, aber nicht zum Lerninhalttyp
4. 2D-Representationen, die zum Lerninhalttyp passen, aber nicht zum Theme
5. Der Rest, also 2D-Representationen, die weder zum Lerninhalttyp noch zum Theme passen
