### ISSUE TITLE
[Technical] UUID für LernWelten, LernRäume und LernElemente in das ATF einbauen

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/Autorentool#302]
Gemäß dem Aktuallisierten ATF 0.4 (Philipp Fragen) müssen für alle Welten, Spaces und Elemente UUIDs im ATF eingefügt werden. 

Zudem müssen diese UUIDs auch im MBZ eingebaut werden (Markus fragen)

**Comment by Glutamat42** [comment]
geht imho -> kann zu?
