### ISSUE TITLE
Lernelement-Dialog zeigt Content-Dateien wie Content-Dialog an

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#305]
**User Story**

Als Lehrender möchte ich, dass Content-Dateien im Lernelement-Dialog wie im Content-Dialog als Tabelle angezeigt werden

 

**Akzeptanzkriterien**

- [x] Alle Content-Dateien werden in der Tabelle angezeigt
- [x] Die Spalten der Tabelle sind verkürzt (kein Delete-Button etc.)

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
Optimized with #541
