### ISSUE TITLE
[Bug] Lernwelten können nicht geladen werden

### ISSUE THREAD

**Issue by MarvinHo64** [ProjektAdLer/Autorentool#313]
## Beschreibung des Problems:
Nach "Import learning world" und auswählen der AWF wird Welt nicht geladen. Dieser Fehler tritt lediglich in Release Version auf, nicht in Entwicklungsumgebung.
## Schritte zum Reproduzieren:
Autorentool öffnen, "Import Learning World" drücken, AFW-Datei auswählen
## Erwartetes Verhalten:
Lernwelt wird geladen
## Tatsächliches Verhalten:
Lernwelt wird nicht geladen
## Ansprechpartner:
Marvin
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/cc57dc42-235c-4e9c-8912-4cbb6142de3c)

**Comment by niklasstich** [comment]
Kann ich auf v1.0.3 nicht reproduzieren, sowohl mit Entwicklungsversion als auch Releaseversion
