### ISSUE TITLE
[Bug] Lernpfade können nicht gelöscht werden

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#321]
## Beschreibung des Problems:
Bei Lernwelten, die in das Autorentool geladen werden, lassen sich die in der Lernwelt erstellten Lernpfade nicht mehr löschen. Auch wenn neue Lernwelten erstellt und gespeichert werden, können die darin befindlichen Lernpfade bei erneutem Öffnen des Autorentools nicht mehr gelöscht werden.
## Schritte zum Reproduzieren:
Autorentool öffnen, "Import Learning World" drücken, AWF-Datei auswählen, geladene Lernwelt öffnen, Lernpfad-Übersicht anklicken, Lernpfade anwählen
oder
Autorentool öffnen, gespeicherte Lernwelt öffnen, Lernpfad-Übersicht anklicken, Lernpfade auswählen
## Erwartetes Verhalten:
Sobald ein Lernpfad angewählt ist und die rote Ellipse geklickt wird, wird der angewählte Lernpfad gelöscht.
## Tatsächliches Verhalten:
Lernpfade lassen sich anwählen, die roten Ellipsen zum Löschen des Lernpfades reagieren aber nicht/leiten keinen Löschvorgang ein.
## Ansprechpartner:
(für weitere Fragen)
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

![Burg-Lernpfade](https://github.com/ProjektAdLer/Autorentool/assets/57803816/1ad4a92c-f0ab-45d6-bb5d-05302d0de1ea)

**Comment by niklasstich** [comment]
Nach Laden der Lernwelt sind die IDs aller LearningPathways Guid.Empty. Da wir die Pathways aber anhand der Guid identifizieren, stürzt der Konstruktor von DeleteLearningPathWay ab.
![image](https://github.com/ProjektAdLer/Autorentool/assets/32730297/a2537cc6-8b3c-4ab4-b65d-aad1ddd43628)
