### ISSUE TITLE
Adaptivitätselement erstellen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#328]
Als Lehrender möchte ich einen Adaptivitätselement mit Multiple Choice-Fragen erstellen können.

 

**Akzeptanzkriterien**

- [x] Tab-Funktion im Reiter "Lernelemente" integrieren
- [x] Kategorie "Allgemein" (Name (Pflichtfeld), Punkte, Arbeitsaufwand)
- [x] Kategorie "Aufgaben" (Button zum Pop-up-Fenster) (Pflichtfeld)
- [x] Darstellung des Adaptivitätselements ähnlich wie ein Lernelement

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/a9b9a695-2716-4ccc-ab53-d8b391dd145c)

**Comment by niklasstich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/328?planning-poker) with Zenhub @andreasweishaupt @e01118 @MarvinHo64 @splican @Teigler

**Comment by niklasstich** [comment]
Create
![image](https://github.com/ProjektAdLer/Autorentool/assets/32730297/39b2dd72-fdea-4355-bdb4-da7db44c1f05)
Update
![image](https://github.com/ProjektAdLer/Autorentool/assets/32730297/27e25c53-ee95-424f-bdef-8355970e53c5)
