### ISSUE TITLE
Lernelement erstellen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#33]
Als Lehrender möchte ich ein Lernelement erstellen können.

 

**Akzeptanzkriterien**

- [x] Zuordnung zu Lernwelt/Lernraum
- [x] Erstellungsdialog
- [x] Anzeigen in View
- [ ] Maus/Finger/Stift?

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by DimitriB01** [comment]
- Aktivitätsdiagramm mit 2 Swimlanes (System, Lehrende)(Ein Aktivitätsdiagramm sind mehrere Akzeptanzkriterien nacheinander)
- Sonderfälle beachten
- Anfangen bei den Daten (welches Format haben die Daten) (Es ginge auch aus der Sicht der Nutzer)

- Alle Requirements in Mural sollen zu UserStories vormuliert sein.

**Comment by MarvinHo64** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/33?planning-poker) with ZenHub @DimitriB01 @e01118 @niklasstich @andreasweishaupt

**Comment by MarvinHo64** [comment]
![grafik](https://user-images.githubusercontent.com/96189400/163982708-47ab4124-b414-4f5b-bf97-f83571a8d2fd.png)
