### ISSUE TITLE
Kommentar in Adaptivitätselement geben

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#332]
Als Lehrender möchte ich zu einer Frage einen Kommentar geben können.
 

**Akzeptanzkriterien**

- [x] Kommentar bei falscher Antwort
- [x] Wenn Autor Kommentar nutzt, ist ein Verweis nicht mehr möglich

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/e2562b03-43e6-4509-a9cd-50cb38633d4c)

**Comment by niklasstich** [comment]
![image](https://github.com/ProjektAdLer/Autorentool/assets/32730297/654012a6-af74-4940-b0c5-5d9b9dd99629)
