### ISSUE TITLE
Verweis in Adaptivitätselement geben

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#333]
Als Lehrender möchte ich zu einer Frage einen Verweis auf ein Lernelement geben können.

 

**Akzeptanzkriterien**

- [x] Verweis auf ein in einem Lernraum platzierten Lernelement ODER Verweis auf externen Lerninhalt
- [x] Verweis nur bei falscher Antwort auf die Frage (nicht bei richtiger Antwort)
- [x] In beiden Fällen (Verweis auf Lernelement oder Lerninhalt) zusätzliches Textfeld (Hinweis)
- [x] Logik: wurde ein Verweis auf ein Lerninhalt bei falscher Antwort gegeben, ist ein Verweis auf ein Lernelement nicht mehr möglich (und andersherum)
- [x] Sortierfunktion der aufgelisteten Lernelemente (z.B. alphabetisch, nach Erstelldatum)
- [x] Wenn Autor Verweis nutzt, ist Kommentar nicht mehr möglich
- [x] Fehlermeldung beim Generieren, wenn Verweis auf Element, welches nicht in einem Raum platziert ist oder in der Halbordnung der Spacereihenfolge in einem Raum, welcher nicht vor dem aktuellen Raum kommt

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/5c6f1aa4-5076-44d3-9b0a-3658901ca649)

![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/8fca60f6-6ea8-40d4-9b22-942fad731fa7)

**Comment by niklasstich** [comment]
![image](https://github.com/ProjektAdLer/Autorentool/assets/32730297/1e274b8c-9659-4b3e-8e8f-8b57ae665f6c)
