### ISSUE TITLE
Fragen in Adaptivitätselement angeben

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#334]
Als Lehrender möchte ich innerhalb einer Aufgabe Fragen erstellen können.

 

**Akzeptanzkriterien**

- [x] Fragen mit leichtem, mittelschwerem und schwerem Schwierigkeitsgrad
- [x] Auswählbar über je einen Button
- [x] Verpflichtende Angabe einer "zu lösenden" Frage (Icon: Schlüssel)
- [x] Nach Erstellen der Frage muss diese wieder löschbar sein (Icon: Mülleimer)
- [x] Multiple und Single Choice mit mehreren Antwortmöglichkeiten (max. 10 Antworten)

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/61b70e7a-7e72-420a-a6bb-ac15176e2e56)

**Comment by andreasweishaupt** [comment]
![image](https://github.com/ProjektAdLer/Autorentool/assets/31248215/222bef26-df5f-4e19-890a-2eea428ff76e)

**Comment by andreasweishaupt** [comment]
![image](https://github.com/ProjektAdLer/Autorentool/assets/31248215/b9a32cb7-337e-473e-80c7-21f8ea63e5f3)
