### ISSUE TITLE
[Technical] Klassendesign für Adaptivitätselement

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#340]
Alle Entwickler zusammen werden das Klassendesign für das Adaptivitätselement anlegen und die entsprechend benötigten Klassen (Entity, Viewmodel, Formmodel, PersistEntity) zusammen implementieren.

**Comment by e01118** [comment]
Aktuelle Version des Konzept zum Autorentool (v0.4): https://cloud.projekt-adler.eu/apps/files/?dir=/AMG/Adaptivit%C3%A4t&fileid=33954

**Comment by e01118** [comment]
Es gibt eine neue Version des Adaptivitätskonzepts zum Autorentool (v08): https://cloud.projekt-adler.eu/apps/files/?dir=/AdLer/Teams/AMG/Adaptivit%C3%A4t&fileid=33954

**Comment by MarvinHo64** [comment]
Stand 17.08.2023
![](https://cdn.discordapp.com/attachments/901018560665649173/1141738419328913509/image.png)

**Comment by niklasstich** [comment]
Neuer Stand nach Vorstellung von Konzept 0.9
![entities_adaptivity](https://github.com/ProjektAdLer/Autorentool/assets/32730297/9aa01baf-4cc8-4ab9-a328-3f12d370a9e7)

**Comment by niklasstich** [comment]
Neuer Stand nach Besprechung mit Marvin (ReferenceAction)
![image](https://github.com/ProjektAdLer/Autorentool/assets/32730297/887bf744-1203-4de9-8065-d0dbc46b232e)
