### ISSUE TITLE
[Bug] Upload kann nicht abgebrochen werden wenn er sich aufhängt

### ISSUE THREAD

**Issue by Glutamat42** [ProjektAdLer/Autorentool#350]
## Beschreibung des Problems:
Ein laufender Upload kann nicht abgebrochen werden, das tool kann nur über den taskmanager beendet werden, da auch der "X" Button nicht klickbar ist
## Schritte zum Reproduzieren:
login mittels http auf einem server der auf https konfiguriert ist. Nun wird sich der Upload einer Welt aufhängen. Dieser kann wie erwähnt nicht abgebrochen werden. Dürfte das selbe sein bei sehr großen Lernwelten / sehr langsamem Internet

## Erwartetes Verhalten:
Ich kann den laufenden upload abbrechen oder zumindest das programm beenden.
## Tatsächliches Verhalten:
Waiting forever
## Ansprechpartner:
Markus
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by niklasstich** [comment]
Zwei separate Probleme, die hier angegangen werden müssen:
1. Bei Fehlschlag des Uploads muss Dialog geupdated werden mit Fehlermeldung bzw. der Progress-Dialog geschlossen und der ErrorHandling Dialog geöffnet werden
2. Der Progress-Dialog braucht einen Cancel-Button => `CancellationToken` bis zu BackendAccess durchreichen und in Progress-Dialog auf `cancelled` setzen
