### ISSUE TITLE
Enter-Taste als Bestätigung für Eingaben

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#356]
Als Lehrender möchte ich Eingaben (z.B. innerhalb der Metadaten) nicht nur über den OK-Button sondern auch über die Enter-Taste bestätigen können

 

**Akzeptanzkriterien**

- [x] Lernwelt-Dialog
- [x] Lernraum-Dialog
- [x] Lernelement-Dialog
- [x] Dateien --> beim Link hinzufügen

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by andreasweishaupt** [comment]
![image](https://github.com/ProjektAdLer/Autorentool/assets/31248215/1371f73a-9804-49e2-92b1-8786d48bbf85)
![image](https://github.com/ProjektAdLer/Autorentool/assets/31248215/52664d68-098d-4c51-b55a-8abc34a93ecc)
![image](https://github.com/ProjektAdLer/Autorentool/assets/31248215/a274c722-2574-429c-aa86-183f217f4c86)
