### ISSUE TITLE
Vorhandene Fragen bei Fragenerstellung in Adaptivitätselement anzeigen

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#373]
**User Story**

Als Lehrender möchte ich beim Erstellen von Fragen bereits erstelle Fragen in anderen Schwierigkeitsgraden angezeigt bekommen, sodass man die Frage in Kontext mit den anderen Schwierigkeitsgraden setzen kann. (Linke Seite in #334)

 

**Akzeptanzkriterien**

- [x] Aufklappbares Fenster in "Frage erstellen" Dialog
- [x] Anzeige der Fragen anderer Schwierigkeitsgrade in selber Aufgabe mit Fragetext und Antwortmöglichkeiten + korrekter Antwort(en)

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/9448e0b0-11b4-4bc2-b3ee-22cbfa3bc900)

**Comment by andreasweishaupt** [comment]
![image](https://github.com/ProjektAdLer/Autorentool/assets/31248215/9bd0b83c-2298-4249-94e2-e7bac7b4c867)
