### ISSUE TITLE
[Bug] Fehlerhafte Anzeige von 3D-Darstellung

### ISSUE THREAD

**Issue by MarvinHo64** [ProjektAdLer/Autorentool#374]
## Beschreibung des Problems:
In dem unten beschrieben Fall wird im Edit Element Dialog statt dem eigentlichen 3D-Modell "l_random" bzw. das Symbol hierfür angezeigt. 
## Schritte zum Reproduzieren:
- In Pfadansicht auf Raum klicken
- Auf Element klicken für das zuvor eine 3D-Darstellung ausgewählt wurde
- Im Edit Learning Element Dialog Menüpunkt "3D-Darstellung des Lernelements" aufklappen
## Erwartetes Verhalten:
Die richtige 3D Darstellung ist ausgewählt. 
## Tatsächliches Verhalten:
l_random oder Symbol hierfür wird angezeigt.
## Ansprechpartner:
Marvin
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by e01118** [comment]
![0-1687439601475](https://github.com/ProjektAdLer/Autorentool/assets/57803816/7b0251b0-d123-41ad-b35a-d8b2db6d2d1d)

**Comment by MarvinHo64** [comment]
In Autorentool Version 2.2.0 nicht reproduzierbar
