### ISSUE TITLE
Vorschau der Frage und Kommentar/Verweis

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#381]
Als Lehrender möchte ich eine Vorschau der erstellten Frage und Kommentar/Verweis angeboten bekommen.

 

**Akzeptanzkriterien**

- [x] Icon Auge mit Hoverfunktion
- [x] erscheint, sobald eine Frage erstellt wurde. 
- [x] Anzeige in der Vorschau enthält erstellte Frage (mit Antworten? - noch nicht geklärt) und erweitert sich mit Angabe des Kommentars oder Verweises (zusätzliches Features zu #372)

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
Beispiel für Vorschau **Frage mit Kommentar**:
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/6981d3f4-8341-4707-b099-5f4339600bd9)

Beispiel für Vorschau **Frage mit Verweis**:
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/4a7efd6f-9d99-401a-8382-7a408dc71eb4)

**Comment by e01118** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/381?planning-poker) with Zenhub @andreasweishaupt @MarvinHo64 @niklasstich

**Comment by andreasweishaupt** [comment]
![image](https://github.com/ProjektAdLer/Autorentool/assets/31248215/14e3c13c-9352-4a0f-9da8-4cf10439b854)
