### ISSUE TITLE
The Witness anschauen

### ISSUE THREAD

**Issue by DimitriB01** [ProjektAdLer/Autorentool#41]
The Witness ist ein Open-World Rätselspiel auf einer Insel, das einen sehr coolen Ansatz verfolgt. Vor allem die Art, wie die Open-World gebaut wurde (Häuser, Türme, Keller, Höhlen, ...), wie neue Gebiete freigeschaltet werden (Leuchtende Kabel auf dem Boden, Türen, etc.) und wie die Rätsel an sich aufgebaut sind (Tafeln, Lichträtsel) könnten coole Inspiration für uns sein, wie so eine Lernwelt aussehen könnte. Rätseln ist ja schließlich auch eine Form von Lernen.

**Comment by niklasstich** [comment]
Full Game Walkthrough: https://www.youtube.com/watch?v=uXrvgHwVKEo
Environment Puzzles (optionaler Content der etwas versteckt ist in den Perspektiven): https://www.youtube.com/watch?v=E_9BF4UqsZQ
