### ISSUE TITLE
Eingabeunterstützung zur Formulierung von Learning-Outcomes integrieren in das Autorentool

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#419]
Als Lehrender möchte ich für die Formulierung von Learning-Outcomes eine Eingabeunterstützung erhalten.
 

**Akzeptanzkriterien**

- [ ] Lernraum-Ebene 
- [ ] (optional) Lernwelt-Ebene

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [ ] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by niklasstich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/419?planning-poker) with Zenhub @andreasweishaupt @e01118 @MarvinHo64 @Teigler

**Comment by MarvinHo64** [comment]
![image](https://github.com/ProjektAdLer/Autorentool/assets/96189400/8bdf540e-ea3b-496f-9f09-3d30d6bbe0f6)
