### ISSUE TITLE
Zip-Ordner hinzufügen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#424]
Als Lehrender möchte ich ganze .zip Archive mit Content auf einmal hinzufügen können (.zip unterstützen und entpacken)
 

**Akzeptanzkriterien**

- [x] .zip Archive mit Content hinzufügen und entpacken
- [x]  Dialog anzeigen, wie viele Dateien hinzugefügt und welche nicht hinzugefügt wurden

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by andreasweishaupt** [comment]
![image](https://github.com/user-attachments/assets/f2086ad1-9c76-4385-896c-36b5fafb29e6)
