### ISSUE TITLE
Neue Anordnung der Dialogfenster zu Elementen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#448]
Als Lehrender möchte ich, dass die Dialogfenster zu den Story-, Lern- und Adaptivitätselementen direkt in der linken Sidebar angeordnet sind und alle unplatzierten Elemente im mittleren Fenster angezeigt werden.
 

**Akzeptanzkriterien**

- [x] Separate Anordnung von (1) Story-, (2) Lern- und (3) Adaptivitätselementen in der linken Sidebar 
- [x] Anordnung der Liste "alle unplatzierten Elemente" im mittleren Fenster unterhalb des Grundrisses

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by niklasstich** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/448?planning-poker) with Zenhub @andreasweishaupt @e01118 @MarvinHo64 @Teigler

**Comment by andreasweishaupt** [comment]
Create Adaptivity Learning Element
![image](https://github.com/ProjektAdLer/Autorentool/assets/31248215/8a086d72-3064-4a39-913b-118a8c0a5a7c)
