### ISSUE TITLE
Storyelement erstellen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#449]
Als Lehrender möchte ich ein Storyelement erstellen können.
 

**Akzeptanzkriterien**

_Allgemein:_
- [x] Insgesamt zwei Elemente / Raum: Eingangs- und Ausgangselement
- [ ] Platzierung der Eingangs- und Ausgangselemente an den beiden Türen des Grundrisses

_Kategorien:_
- [x] Kategorie "Allgemein" mit _Titel der Story_ (optional) und _Text zur Story_ (Pflichtfeld)
- [x] Kategorie "3D-Darstellung" (optional)

_Regeln zur 3D-Darstellung:_
1. [x] Wird das Element direkt im Space erstellt, dann ist standardmäßig immer der NPC ausgewählt, der zum Theme des jeweiligen Lernraums passt (Theme "Spielhalle" = Sheriff, Theme "Vorstadt" = weiblicher NPC, Theme "Campus" = männlicher NPC)
2. [x] Wurde erst ein Storyelement angelegt, bevor es überhaupt einen Lernraum gibt, dann ist standardmäßig immer der männliche NPC ausgewählt. (Es gibt kein Random, folglich kann Random nicht ausgewählt sein und es muss der männliche NPC sein)
3. [ ] (on hold) Wählt der Autor im ersten Raum, in dem er ein Storyelement anlegt, einen anderen NPC aus als vorgesehen, wird der Autor gefragt, ob er diesen NPC auch für alle anderen Storyelemente nutzen möchte und die Auswahl für alle weiteren Storyelemente übernommen werden soll.

_Darstellung erstellter Storyelemente:_
- [ ] Einbetten des Story-Icons in die MudCard zum Storyelement: https://cloud.projekt-adler.eu/s/J7HJY9En5FMr66i
- [x] Einbetten des ausgewählten NPCs in die MudCard zum bestätigten Storyelement -> siehe #458 
- [x] Anzeigen des Titels in der MudCard (wie bei Lernelementen) --> wenn kein Titel angegeben wurde, erscheint "Story-Eingangselement" oder Story-Ausgangselement" mit der jeweiligen Nummerierung, falls es bereits mehrere gibt.
- [ ] #486 

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [ ] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by e01118** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/449?planning-poker) with Zenhub @andreasweishaupt @MarvinHo64 @niklasstich @splican @Teigler

**Comment by niklasstich** [comment]
1. StoryContent kann wie AdaptivityContent nicht vorher erstellt werden, sondern erst im Dialog (wie im Designdokument)
2. Abklären mit 3D, wer den String in Sprechblasen splittet (z.B. per Absatz oder Spezialzeichen)
