### ISSUE TITLE
[Technical] 3D-Darstellungen in erstellten Story-, Lern- und Adaptivitätselementen anzeigen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#458]
Sobald ein Element erstellt wurde und in die Liste aller Elemente platziert wird, soll die jeweilige angegebene 3D-Darstellung in dem Element mit dargestellt werden.

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/0139e592-bf63-4bd9-8986-5b5ea8aa236b)

**Comment by e01118** [comment]
Lösung:
![grafik](https://github.com/user-attachments/assets/9d2bca4d-3019-4e91-afde-9aa21d4ce188)

**Comment by e01118** [comment]
Andere Lösung (scale-75 2xl:scale-80 absolute -top-5):
![grafik](https://github.com/user-attachments/assets/3b8a8477-156e-4ed7-8400-1cdf1c258cbb)

**Comment by splican** [comment]
Auf Karten begrenzte 3D-Darstellung wäre meine Wahl.
