### ISSUE TITLE
[Bug] Keine Begrenzung auf max. 50 Lernräume pro Welt

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#501]
## Beschreibung des Problems:
Von Moodle vorgegeben gibt es eine maximale Anzahl von 52 möglichen Sections pro Kurs (siehe https://moodledev.io/general/releases/3.10/3.10.1). Da wir zwei Sections für spezielle Aufgaben benötigen (externer Content und "Raum 0"(?)), bleiben uns noch max. 50 Lernräume pro Welt
## Schritte zum Reproduzieren:
N/A
## Erwartetes Verhalten:
N/A
## Tatsächliches Verhalten:
N/A
## Ansprechpartner:
@Glutamat42 @niklasstich 
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by Glutamat42** [comment]
In "Raum 0" werden Lernweltinfos angezeigt, die sonst nicht sinnvoll in Moodle unterzubringen sind (zumindest nicht ohne custom theme oder sowas)
