### ISSUE TITLE
[Bug] Fehler beim eingeben einer neuen API URL

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/Autorentool#510]
## Beschreibung des Problems:
Das Autorentool wirft einen Fehler, wenn ich eine neue API URL im Administration Modal eingeben möchte.
## Schritte zum Reproduzieren:
Autorentool öffnen > Es muss bereits eine URL im Administration Modal eingetragen sein. Diese ist in meinem Fall aber gerade nicht erreichbar (Mein Homeserver hat ein Problem). Deshalb möchte ich die URL auf die des AdLer Servers ändern. Schritte: Autorentool öffnen > Administrator Modal öffnen > Klick in die Zeile AdLer API URL > Fehler (siehe Screenshot)
## Erwartetes Verhalten:
Ich kann eine neue URL eintragen
## Tatsächliches Verhalten:
Fehler erscheint. Wenn ich "Neu Laden" klicke passiert wieder das gleiche und ich kann keine neue URL eingeben.
## Ansprechpartner:
Daniel Glaab
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

[relevanter-log.txt](https://github.com/ProjektAdLer/Autorentool/files/14852786/relevanter-log.txt)
![screenshot_bug_neue_URL_eingeben](https://github.com/ProjektAdLer/Autorentool/assets/99543798/1f184e08-be55-4e90-a0e5-1dcac9439fa2)

**Comment by MarvinHo64** [comment]
Reproduziert mit den folgenden Schritten:

1. Autorentool öffnen und über Backend in Moodle anmelden
2. Autorentool schließen
3. Moodle Docker stoppen 
4. Autorentool erneut öffnen
5. Anmeldedialog öffnen

[errorLog.txt](https://github.com/user-attachments/files/17488438/errorLog.txt)
