### ISSUE TITLE
[Bug] Fehler bei Hochladen der Lernwelt wenn Token ungültig ist

### ISSUE THREAD

**Issue by MarvinHo64** [ProjektAdLer/Autorentool#519]
## Beschreibung des Problems:
Wenn das Autorentool nach längerer Zeit (nach Ablauf der gültigkeit des Moodle Token) geöffnet wird, und versucht wird, eine Lernwelt hochzuladen, wird ein Fehler geworfen, der nicht gefangen wird.
## Schritte zum Reproduzieren:
siehe Log-Datei:
[240422_Log.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdytBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b9dbf659503dff77af70e9eb43dadf8041de1ec/240422_Log.txt)

## Erwartetes Verhalten:
(Erwartetes Verhalten nach eigenem Verständnis)
## Tatsächliches Verhalten:
(ausführliche Beschreibung des Fehlerverhaltens, falls möglich. Gerne auch Screenshot, Log, etc.)
## Ansprechpartner:
@MarvinHo64 
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by andreasweishaupt** [comment]
Der nicht gefangene Fehler tritt auch auf, wenn ein Token existiert, aber das Backend nicht erreichbar ist.
