### ISSUE TITLE
Lernwelt in Toolbox suchen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#53]
Als Lehrender möchte ich eine Lernwelt in der Toolbox suchen können.

 

**Akzeptanzkriterien**

- [x] Alle in der Toolbox abgelegten Welten sollen angezeigt werden
- [x] Beim Eingeben eines Suchbegriffs sollen alle zutreffenden Welten angezeigt werden

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Benutzerdokumentation angelegt (Handbuch)
- [ ] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by niklasstich** [comment]
![image](https://user-images.githubusercontent.com/32730297/175501157-d96e53d9-d76f-47bb-be08-2773045c2e54.png)

**Comment by niklasstich** [comment]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/32730297/197873349-1329d7d3-2a8b-498c-9d08-abddeaa3e0b2.png">
