### ISSUE TITLE
[UI] Fehlende Localizer-Einträge

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#535]
## Beschreibung des Problems:
In einigen Dialogen sind noch keine Localizer-Einträge, die noch nachträglich ergänzt werden müssen.

## Tatsächliches Verhalten:
 - [x] Schließen des Autorentools (Unsaved changes!) --> AuthoringToolWorkspacePresenter.cs
 - [x] Schließen des Autorentools (Unsaved changes!) --> AuthoringToolWorkspacePresenterUt.cs
 - [x] Datei leer --> ContentFilesAdd
 - [x] Unsupported fileending --> ContentFilesAdd
 - [x] Rechtsklickmenü
 - [x] Multiple/Single Choice --> MultipleChoiceQuestionValidator.cs
 - [x] Learning Content darf nicht leer sein --> TableSelect und MudFormComponent.cs
 - [x] Must only contain... --> Alphanumeric Validator.cs
 - [x] Must only contain... --> Name Validator.cs
 - [x] NoContentWarning.Text (Localizer) --> Lernmaterial statt Lerninhalte

## Ansprechpartner:
(für weitere Fragen)
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/90429b23-8b01-4a70-a5dc-3c1deee96106)

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/fef00630-edb5-4495-9087-9f9c85326b17)

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/19a00268-5598-4892-95d4-3257ac34fbe4)

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/a72334d1-4a04-4750-a01d-4a990c009c3b)

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/595158ee-8cce-474e-98e4-bf90ed0f52db)

**Comment by e01118** [comment]
![grafik](https://github.com/ProjektAdLer/Autorentool/assets/57803816/f1120cd1-15cf-4585-a970-65a2cd5811aa)

**Comment by e01118** [comment]
![grafik](https://github.com/user-attachments/assets/a595afcd-c29a-40d6-bde1-7925656323f3)

**Comment by e01118** [comment]
![grafik](https://github.com/user-attachments/assets/975a8311-009d-4536-a5ea-87e80e0ac84b)

**Comment by MarvinHo64** [comment]
Wenn ein bereits existierender ext. Lerinhalt hinzugefügt wird:

<img width="552" alt="Bildschirmfoto 2024-10-31 um 14 50 14" src="https://github.com/user-attachments/assets/79bb607f-94c2-4696-8935-0747ec32061b">

**Comment by e01118** [comment]
Fehlender Localizer:
![grafik](https://github.com/user-attachments/assets/a8b64ad5-9cae-4580-a7bd-ba452f0334bd)

Localizer:
