### ISSUE TITLE
[Bug] Fehlende Meldung bei Lernelementen ohne Lernmaterial

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#547]
## Beschreibung des Problems:
Wenn man ein Lernelement ohne zugewiesenem Lernmaterial hat, erscheint keine Meldung im Lernelement-Dialog, wenn ein Lernelement angewählt ist.
## Schritte zum Reproduzieren:
Lernmaterial hochladen --> Lernmaterial einem Lernelement zuweisen --> Lernmaterial löschen --> Lernelement anklicken
## Erwartetes Verhalten:
Zukünftig:
- Zusätzlich soll in der Fehlermeldung darauf hingewiesen werden, dass auch das dazugehörige Lernelement gelöscht wird und 
- das Lernelement muss auch gelöscht werden.
- Beim Öffnen des Autorentools muss in den jeweiligen Lernwelten das Vorhandensein von Lernelementen und deren zugewiesenen Dateien geprüft werden.
## Tatsächliches Verhalten:
Bisher: Wenn Lernmaterial gelöscht werden soll, dann erscheint eine Warnmeldung mit der Abfrage, ob diese wirklich gelöscht werden sollen und dem Hinweis, dass auch die dazugehörigen Lernelemente gelöscht werden.
## Ansprechpartner:
(für weitere Fragen)
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by MarvinHo64** [comment]
Um einen konsistenten Zustand bzgl. der Verbindung von Lernelementen und deren LearningContent zu erreichen ist eine Neuplanung in Form einer User Story (https://github.com/ProjektAdLer/Autorentool/issues/644) notwendig.
