### ISSUE TITLE
[Bug] Text-UI-Elemente lassen sich markieren/auswählen und verschieben

### ISSUE THREAD

**Issue by BujusKrachus** [ProjektAdLer/Autorentool#581]
## Beschreibung des Problems:
_für https://github.com/ProjektAdLer/Autorentool/releases/tag/2.1.7_

wie im Video zu sehen, lassen sich UI Text Elemente selektieren und bewegen. In Kombination mit dem Bewegen eines eigentlich bewegbaren Elements kann dies schnell zu Verwirrung führen. Lässt sich dies irgendwie deaktivieren/umgehen?

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDRZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d039d79ec4d2251ed3ca988b3ed29aa59675009/selektionBewegen.mp4)

## Schritte zum Reproduzieren:
- ctrl + a (als einfaches Beispiel. geht uch einzeln oder per Zufall durch Unachtsamkeit)
- bewegen und Spaß haben. Fyi Bewegung ist gesund ;)
## Erwartetes Verhalten:
(Erwartetes Verhalten nach eigenem Verständnis)
## Tatsächliches Verhalten:
(ausführliche Beschreibung des Fehlerverhaltens, falls möglich. Gerne auch Screenshot, Log, etc.)
## Ansprechpartner:
(für weitere Fragen)
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by e01118** [comment]
Erledigt mit #622
