### ISSUE TITLE
[Bug - von RR] - Lokalisierung in Lernwelt hochladen Modal

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/Autorentool#600]
## Beschreibung des Problems:
Im Lernwelt hochladen Modal ist noch der englische Text "Uploading World" zu lesen.
## Schritte zum Reproduzieren:
Lernwelt hochladen - Modal erscheint
## Erwartetes Verhalten:
Lokalisierung der Texte auf Deutsch
## Tatsächliches Verhalten:
s.o.
## Ansprechpartner:
@splican 
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by e01118** [comment]
Lösung:
![grafik](https://github.com/user-attachments/assets/1655bc49-856a-4a3e-babd-9fefac92fe19)
