### ISSUE TITLE
[Bug - von RR] - Bestätigungsdialog Lernwelt aus LMS löschen

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/Autorentool#602]
## Beschreibung des Problems:
Der Bestätigungsdialog zur Funktion Lernwelt aus LMS löschen sollte laut Raphael auch einen roten Warnhinweis bekommen. Wie unter "Lernwelt speichern/überschreiben".
## Schritte zum Reproduzieren:
Lernwelt aus Moodle löschen > Dann Bestätigungsdialog
## Erwartetes Verhalten:
Sollte roten Warnhinweis haben
## Tatsächliches Verhalten:
kein roter Warnhinweis
## Ansprechpartner:
@splican 
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by e01118** [comment]
Ist Teil von #618
