### ISSUE TITLE
[Bug - von RR] - Element-Karte/Slots Button

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/Autorentool#605]
## Beschreibung des Problems:
(Element-Karte/Slots im Autorentool schlechter Kontrast) TODO: RR: Dieser Button hat einen schlechten Kontrast, daher ev. nicht barrierefrei
## Schritte zum Reproduzieren:
(bitte möglichst *genaue* Beschreibung, wie und unter welchen Umständen das Problem reproduziert werden kann und, falls nötig, relevante Dateien anhängen)
## Erwartetes Verhalten:
(Erwartetes Verhalten nach eigenem Verständnis)
## Tatsächliches Verhalten:
(ausführliche Beschreibung des Fehlerverhaltens, falls möglich. Gerne auch Screenshot, Log, etc.)
## Ansprechpartner:
(für weitere Fragen)
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by e01118** [comment]
Bisheriger Zustand:
![grafik](https://github.com/user-attachments/assets/7f871ff0-854d-460e-b88b-186693ab24af)


Verbesserung:
![grafik](https://github.com/user-attachments/assets/7310384e-8412-42a0-81f6-24f009878675)
