### ISSUE TITLE
Rechtsklickmenü per Linksklick schließen

### ISSUE THREAD

**Issue by MarvinHo64** [ProjektAdLer/Autorentool#606]
## Beschreibung der Verbesserung:
Das Rechtsklickmenü für Lernelemente und Lernräume sollte sich per Linksklick schließen lassen.
## Schritte zum Reproduzieren:
1. Lernraum öffnen 
2. Rechtsklick auf Lernelement
3. Außerhalb des Lernelements links klicken
## Erwartetes Verhalten:
Menü schließt sich
## Tatsächliches Verhalten:
Menü schließt sich nicht
## Ansprechpartner:
@MarvinHo64

**Comment by e01118** [comment]
Verweis auf #609
