### ISSUE TITLE
[Bug] einfache Lernelemente werden mit falschen completion conditions erstellt

### ISSUE THREAD

**Issue by Glutamat42** [ProjektAdLer/Autorentool#664]
## Beschreibung des Problems:
Einfache Lernelemente ("resource") werden mit der completion condition "manual" erstellt werden. Dieses Verhalten ist vom plugin_release_set 4.0.0 nicht mehr unterstützt und es findet auch keine Konvertierung zu den neuen completion conditions statt. Dies führt dazu, dass es nicht mehr möglich ist diese Lernelemente über 3D abzuschließen.

[testwelt.zip](https://github.com/user-attachments/files/17997025/testwelt.zip)

![grafik](https://github.com/user-attachments/assets/8d49ef35-354f-4c67-8363-b99b2c62b078)
-> müsste auf "view" stehen

## Schritte zum Reproduzieren:
(bitte möglichst *genaue* Beschreibung, wie und unter welchen Umständen das Problem reproduziert werden kann und, falls nötig, relevante Dateien anhängen)
## Erwartetes Verhalten:
(Erwartetes Verhalten nach eigenem Verständnis)
## Tatsächliches Verhalten:
(ausführliche Beschreibung des Fehlerverhaltens, falls möglich. Gerne auch Screenshot, Log, etc.)
## Ansprechpartner:
(für weitere Fragen)
## Ursache (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Lösung (erst bei Fix angeben): 
(wird durch Team AMG ausgefüllt)
## Commit, in dem das Problem gefixed wurde:  
(wird durch Team AMG ausgefüllt)

**Comment by MarvinHo64** [comment]
Fixed mit 449fa14836504d167fefd1f5244d860859171f18
