### ISSUE TITLE
Leere Lernwelt vom Autorentool für Moodle generieren

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#67]
Der Generator muss Lernwelten in Moodle generieren können.

 

**Akzeptanzkriterien**

- [x] Es ist möglich eine Moodle Backup Datei, welche eine Leere Lernwelt beinhaltet, mithilfe eines Buttons zu erstellen

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by DimitriB01** [comment]
Die Dateien die mindestens für einen Moodle Kurs (Lernwelt) notwendig sind, wurden dokumentiert: https://wiki.cluuub.xyz/de/moodle/Moodle-Backup-Leerer-Kurs

**Comment by DimitriB01** [comment]
![API](https://user-images.githubusercontent.com/92084464/164016981-b4c7a4c3-28a1-4c4b-9dd2-ede3e41c511e.png)
![Entities](https://user-images.githubusercontent.com/92084464/164016986-39457019-ff39-46e3-93d2-1e877bc6059c.png)
![WorldExport](https://user-images.githubusercontent.com/92084464/164016988-0c12f9f2-8740-448b-87e0-973fef8d23d1.png)
![XmlClasses](https://user-images.githubusercontent.com/92084464/164016990-0b5212f5-466c-46f9-a7bf-5560d9e0d235.png)

**Comment by DimitriB01** [comment]
![API](https://user-images.githubusercontent.com/92084464/164259101-c5c6e779-cde3-47f4-953e-03655545a4e9.png)
![Entities](https://user-images.githubusercontent.com/92084464/164259108-31521cbe-aaa5-472f-9746-b34cc0e0a8b1.png)
![WorldExport](https://user-images.githubusercontent.com/92084464/164259109-2a25ee24-2b4d-4c31-a161-33f5bf3ecb10.png)
![XmlClasses](https://user-images.githubusercontent.com/92084464/164259112-bc8a74a1-602d-480e-b8bf-8b14a25ef346.png)
