### ISSUE TITLE
Themenbereich in Moodle generieren

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#71]
Der Generator muss Themenbereiche in Moodle generieren können.

 

**Akzeptanzkriterien**

- [x] Themenbereich (Section) wird korrekt in Moodle an der richtigen Stelle erstellt
- [ ] Themenbereich beinhaltet alle zugewiesenen Lernräume und Lernelemente
- [x] Themenbereich kann eine Moodle-Beschreibung erhalten

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Benutzerdokumentation angelegt (Handbuch)
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by DimitriB01** [comment]
Das Kriterium: "Themenbereich beinhaltet alle zugewiesenen Lernräume und Lernelemente" kann noch nicht abgeschlossen werden. Da im Autorentool derzeit keine Themenbereiche erstellt werden können. Im Moment werden alle Lernräume aus dem Autorentool in Moodle als Section erstellt. 

Nachdem Themenbereiche zum Autorentool hinzugefügt werden, muss diese User Story angepasst werden, sodass nicht mehr aufgrund von Lernräumen Sections erstellt werden.

**Comment by DimitriB01** [comment]
![image](https://user-images.githubusercontent.com/92084464/188443355-a381c548-b70c-4923-9b77-2067b301cb52.png)

**Comment by niklasstich** [comment]
Blockiert, bis #58 im Autorentool implementiert ist

**Comment by MarvinHo64** [comment]
Themenbereiche werden vorerst nicht in Moodle dargestellt. Stattdessen LearningSpaces als Sections

**Comment by e01118** [comment]
#old - will not be implemented
