### ISSUE TITLE
extern erstellte Lernelementinhalte per Drag and Drop hinzufügen

### ISSUE THREAD

**Issue by e01118** [ProjektAdLer/Autorentool#83]
Als Lehrender möchte ich Dateien, die Lernelementinhalte sein können (Videodateien, Bilddateien, etc.), per Drag und Drop als neues Lernelement hinzufügen.

**Akzeptanzkriterien**

- [x] Dateien können per Drag and Drop in den Workspace gezogen werden
- [x] Lernelement erstellen Dialog mit bereits ausgewähltem Typ und eingebundener Datei öffnen
- [ ] Bei nicht unterstützter Dateiendung wird eine Fehlermeldung angezeigt

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [ ] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Benutzerdokumentation angelegt (Handbuch)
- [ ] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by andreasweishaupt** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AutorentoolWS-61b750ce1832a500135474ec/issues/ProjektAdLer/Autorentool/83?planning-poker) with ZenHub @e01118 @MarvinHo64 @niklasstich

**Comment by niklasstich** [comment]
Funktionalität ist bereits implementiert, aber wir wollen die Implementierung noch wie in #110 beschrieben verfeinern.

**Comment by andreasweishaupt** [comment]
Da das Drag and Drop auf MudBlazor umgestellt wird, wird die fehlende Dokumente nach dem UI-Rework gesammelt erledigt.
