### ISSUE TITLE
Moodle Generator Akzeptanzkriterien

### ISSUE THREAD

**Issue by niklasstich** [ProjektAdLer/Autorentool#96]
Aktivitätsdiagramme für alle Use Cases der Form "Lern[welt] vom Autorentool in Moodle generieren"
sowie andere Akzeptanzkriterien feststellen

**Comment by DimitriB01** [comment]
Wurde zum großen UML-Diagramm auf dem NAS in Aschaffenburg hinzugefügt.

**Comment by DimitriB01** [comment]
Nach Error, muss ein Endzustand drin sein
