### ISSUE TITLE
Oberfläche für Autorentool

### ISSUE THREAD

**Issue by andreasweishaupt** [ProjektAdLer/Autorentool#97]
Als Lehrender möchte ich die existierenden Lernelemente, Lernräume und Lernwelten in der Oberfläche sehen und bearbeiten können.

 

**Akzeptanzkriterien**

- [x] A1: Lernelemente, -räume und -welten müssen auf der Oberfläche dargestellt werden können.
- [x] A2: Lernelemente, -räume und -welten müssen auf der Oberfläche ausgewählt werden können.
- [x] A3: Lernraum kann geöffnet und dessen Inhalt im Workspace angezeigt und bearbeitet werden
- [x] A4: Maus
Finger und Stiftsupport ist zunächst nicht vorgesehen, da die meisten Betriebssysteme dies jedoch transparent unterstützen müssen wir hier keine zusätzliche Funktionalität einprogrammieren. Wir achten lediglich darauf, Bedienelemente gut benutzbar für jegliche Art von Gerät und Bedienmöglichkeit zu machen

 **Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

 
**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by niklasstich** [comment]
Wird eventuell an HiWis abgegeben!

**Comment by niklasstich** [comment]
Wird doch nicht an HiWis abgegeben, wir schreiben die Tests lieber selber.

**Comment by niklasstich** [comment]
Geschlossen da Testabdeckung (für jetzt) einen ersten akzeptablen Wert erreicht hat.
